
language: python
python:
  - "3.9"

branches:
  only:
  - main

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"