version: '3'

services:
  app:
    image: travels_app:v1.0.0
    container_name: travels_app
    build:
      context: .
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
volumes:
  postgres-data:
