# Generated by Django 3.2.8 on 2021-10-27 22:18

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.travel_image_file_path)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('countInStock', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
