# Generated by Django 3.2.8 on 2021-10-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_travel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
