# Generated by Django 3.2.8 on 2021-10-31 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_travel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
