# Generated by Django 3.2.8 on 2021-10-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_travel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
